"""FastAPI artifact generator: dependency closure + adapter + contract + wheel.

Produces a "three-part wheel" for each approved API:
  1. runnable app  (``app/``)          — FastAPI service + stable schemas + adapter
  2. dependency closure (``<pkg>/``)   — legacy source copied in as importable package
  3. readable contract (``app/contract/``) — api-contract.json + provenance
"""
from __future__ import annotations

import ast
import datetime
import json
import re
import subprocess
import sys
import uuid
from pathlib import Path

import yaml

from git_asset_mcp.packagers.fastapi.contract import contract_hash, implementation_hash
from git_asset_mcp.proposal.schemas import ApiProposal
from git_asset_mcp.providers.base import RepositoryProvider
from git_asset_mcp.store.database import Database

TEMPLATE_VERSION = "0.1.0"

# 文件级闭包中包的 __init__.py 使用生成的最小版本（原文件的 re-export 会
# 触发全量子模块依赖，导致只装入口子模块时 import 断链）。
_MINIMAL_INIT = '"""Generated by git-asset-mcp. Minimal package init."""\n'


def _minimal_openapi(proposal: ApiProposal, api_name: str, version: str) -> dict:
    return {
        "openapi": "3.1.0",
        "info": {"title": api_name, "version": version},
        "paths": {
            proposal.path: {
                proposal.method.lower(): {
                    "requestBody": {
                        "content": {"application/json": {"schema": proposal.request_schema}}
                    },
                    "responses": {
                        "200": {
                            "description": "ok",
                            "content": {
                                "application/json": {"schema": proposal.response_schema}
                            },
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }


# ---------------------------------------------------------------------------
# dependency closure
# ---------------------------------------------------------------------------

def _closure_info(entry_path: str) -> tuple[str, str, str]:
    """Derive ``(pkg_dir, package_name, import_module)`` from the entry file path.

    Works with or without a leading source-root segment:
      ``src/legacy_checkout/checkout.py`` -> package ``legacy_checkout``, module ``legacy_checkout.checkout``
      ``order_api/validation.py``         -> package ``order_api``,        module ``order_api.validation``
    """
    parts = entry_path.replace("\\", "/").split("/")
    pkg_dir = "/".join(parts[:-1])
    package_name = pkg_dir.split("/")[-1]
    filename = parts[-1]
    # __init__.py 作为入口时，import 目标是包本身（openai），而非 openai.__init__
    if filename == "__init__.py":
        submodule = ""
    else:
        submodule = filename[:-3] if filename.endswith(".py") else filename
    import_module = f"{package_name}.{submodule}" if submodule else package_name
    return pkg_dir, package_name, import_module


def _resolve_import_target(
    module_name: str | None, pkg_dir: str, package_name: str, tree: set[str],
    current_path: str = "", level: int = 0,
) -> str | None:
    """Resolve a same-package import to a repo file path inside ``tree``.

    Handles ``import legacy_checkout.pricing`` /
    ``from legacy_checkout.discount import dsc`` (absolute, same package)
    and relative imports (``level > 0``, e.g. ``from .assistants import x``
    resolves against the current file's package directory, so nested
    subpackages work too). Returns ``None`` for third-party /
    out-of-package imports.
    """
    if not module_name:
        return None
    if level > 0:
        # 相对导入：AST 中 module 已去掉点前缀，level 表示向上层级
        rest = module_name.strip(".")
        cur_dir = "/".join(current_path.replace("\\", "/").split("/")[:-1])
        if current_path.endswith("__init__.py"):
            base = cur_dir
        else:
            base = "/".join(cur_dir.split("/")[:-1]) if "/" in cur_dir else ""
        for _ in range(max(level - 1, 0)):
            base = "/".join(base.split("/")[:-1]) if "/" in base else ""
        rel_parts = [p for p in rest.split(".") if p]
        if not rel_parts:
            return None
        leaf = rel_parts[-1]
        parent = "/".join([base] + rel_parts[:-1]) if len(rel_parts) > 1 else base
        for cand in (f"{parent}/{leaf}.py", f"{parent}/{leaf}/__init__.py"):
            if cand in tree:
                return cand
        return None
    if not module_name.startswith(package_name):
        return None
    rel = module_name[len(package_name):].strip(".")
    parts = [p for p in rel.split(".") if p]
    if not parts:
        return None
    base = pkg_dir + "/" + "/".join(parts)
    for cand in (base + ".py", base + "/__init__.py"):
        if cand in tree:
            return cand
    return None


def _package_closure(
    provider: RepositoryProvider, repo_id: str, commit: str,
    pkg_dir: str, package_name: str, entry_path: str,
) -> tuple[dict[str, str], list[str]]:
    """Copy the entry file plus its same-package imports into the artifact.

    File-level closure with AST import resolution: bundles the file containing
    the API entry, any ``__init__.py`` keeping the package importable, and
    every same-package module the entry transitively imports. Third-party or
    out-of-package imports are not pulled in.

    Returns ``(files, blob_shas)`` where ``files`` maps the wheel-relative path
    (under ``package_name``) to source text.
    """
    tree: dict[str, tuple[str, str]] = {}
    for path, blob_sha in provider.ls_tree(repo_id, commit):
        if path.startswith(pkg_dir + "/") and path.endswith(".py"):
            tree[path] = (provider.read_blob(repo_id, blob_sha), blob_sha)

    want: set[str] = {entry_path}
    queue = [entry_path]
    while queue:
        path = queue.pop()
        item = tree.get(path)
        if item is None:
            continue
        try:
            module = ast.parse(item[0])
        except SyntaxError:
            continue
        for node in ast.walk(module):
            target: str | None = None
            if isinstance(node, ast.Import):
                for alias in node.names:
                    target = _resolve_import_target(alias.name, pkg_dir, package_name, set(tree), path)
                    if target and target not in want:
                        want.add(target)
                        queue.append(target)
            elif isinstance(node, ast.ImportFrom) and node.module:
                target = _resolve_import_target(node.module, pkg_dir, package_name, set(tree), path, getattr(node, "level", 0))
                if target and target not in want:
                    want.add(target)
                    queue.append(target)

    for path in tree:
        if path.endswith("__init__.py"):
            want.add(path)

    files: dict[str, str] = {}
    blob_shas: list[str] = []
    # 入口文件本身是包的 __init__.py 时（如 openai/__init__.py 定义入口函数），
    # 保留包内全部 __init__.py 原文件——re-export 链依赖子包符号，
    # 最小化会导致 import 断链。
    preserve_all_init = entry_path.endswith("__init__.py")
    for path in sorted(want):
        rel = path[len(pkg_dir) + 1:]
        if path.endswith("__init__.py") and not preserve_all_init and path != entry_path:
            # 非入口包 __init__ 最小化：原文件的 re-export 会触发全量子模块
            # 依赖，文件级闭包只装入口子模块，故用生成的空 init 保持包结构。
            # 该文件是模板产物，不纳入源码指纹（blob_shas）。
            files[f"{package_name}/{rel}"] = _MINIMAL_INIT
        else:
            source, blob_sha = tree[path]
            files[f"{package_name}/{rel}"] = source
            blob_shas.append(blob_sha)
    return files, blob_shas


def _parse_entry_params(signature: str) -> list[tuple[str, str | None]]:
    """Parse ``def f(a, b='x', c=None) -> ...`` into [(name, default_literal_or_None)]."""
    m = re.search(r"\((.*)\)", signature)
    if not m:
        return []
    params: list[tuple[str, str | None]] = []
    for p in m.group(1).split(","):
        p = p.strip()
        if not p or p == "self":
            continue
        default = None
        name_part = p
        if "=" in p:
            name_part, default = p.split("=", 1)
            name_part = name_part.strip()
            default = default.strip()
        if ":" in name_part:
            name_part = name_part.split(":", 1)[0].strip()
        if name_part:
            params.append((name_part, default))
    return params


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------

def build_artifact(
    proposal: ApiProposal,
    provider: RepositoryProvider,
    db: Database,
    version: str,
    generated_dir: Path,
    build_wheel: bool = False,
) -> dict:
    """Package an approved proposal into an immutable version directory (+ optional wheel)."""
    if proposal.status != "approved":
        raise RuntimeError("proposal_not_approved")

    artifact_dir = generated_dir / proposal.api_name / version
    if artifact_dir.exists():
        raise RuntimeError("version_exists")

    existing = db.find_artifact_by_symbols(sorted(proposal.entry_symbols))
    if existing and existing.get("module_id") != proposal.module_id:
        raise RuntimeError(f"duplicate_asset: already covered by {existing['artifact_id']}")

    repo_id = proposal.module_id.split(":", 1)[0]
    commit = proposal.source_paths and _commit_for(db, repo_id)

    entry_qname = proposal.entry_symbols[0]
    # 入口文件：按符号查（优先），fallback 到提案的第一个源文件路径
    entry_paths = db.source_paths_for_symbols(repo_id, {entry_qname})
    entry_path = next(iter(sorted(entry_paths))) if entry_paths else proposal.source_paths[0]
    pkg_dir, package_name, import_module = _closure_info(entry_path)
    func_name = entry_qname.split(".")[-1]
    signature = db.get_symbol_signature(repo_id, commit or "", entry_qname) or ""
    params = _parse_entry_params(signature)

    # dependency closure (entry file + package __init__) + its blob shas
    closure_files, closure_blobs = _package_closure(
        provider, repo_id, commit or "", pkg_dir, package_name, entry_path
    )
    entry_blobs = db.blob_shas_for_paths(repo_id, commit or "", proposal.source_paths) if commit else []
    all_blobs = sorted(set(entry_blobs + closure_blobs))

    artifact_dir.mkdir(parents=True, exist_ok=False)
    app_dir = artifact_dir / "app"
    (app_dir / "contract").mkdir(parents=True)
    (app_dir / "__init__.py").write_text("", encoding="utf-8")

    adapter_source = _render_adapter(import_module, func_name, params)
    (app_dir / "adapter.py").write_text(adapter_source, encoding="utf-8")
    (app_dir / "schemas.py").write_text(_render_schemas(proposal), encoding="utf-8")

    openapi = _minimal_openapi(proposal, proposal.api_name, version)
    chash = contract_hash(openapi)
    ihash = implementation_hash(all_blobs, adapter_source, TEMPLATE_VERSION)

    (app_dir / "main.py").write_text(
        _render_main(proposal, version, chash, ihash, commit or ""), encoding="utf-8"
    )

    # dependency closure package (importable, keeps original import statements intact)
    for rel, source in closure_files.items():
        out = artifact_dir / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(source, encoding="utf-8")

    # readable contract + provenance (inside the app package so they ship in the wheel)
    (app_dir / "contract" / "api-contract.json").write_text(
        _render_contract(proposal, import_module, func_name, signature, params, version),
        encoding="utf-8",
    )
    (app_dir / "contract" / "source-provenance.json").write_text(
        _render_provenance(proposal, version, commit or "", all_blobs, closure_files), encoding="utf-8"
    )

    # top-level artifacts for inspection (also duplicated into the wheel via package-data)
    (artifact_dir / "openapi.json").write_text(_json_dumps(openapi), encoding="utf-8")
    (artifact_dir / "asset-manifest.yaml").write_text(
        _render_manifest(proposal, version, chash, ihash, commit or ""), encoding="utf-8"
    )
    (artifact_dir / "source-provenance.json").write_text(
        _render_provenance(proposal, version, commit or "", all_blobs, closure_files), encoding="utf-8"
    )
    (artifact_dir / "pyproject.toml").write_text(
        _render_pyproject(proposal, version, ["app", package_name] if package_name else ["app"]),
        encoding="utf-8",
    )

    # build the wheel into dist/ (optional; off by default to keep tests fast)
    wheel_path = _build_wheel(artifact_dir, generated_dir.parent / "dist") if build_wheel else ""

    artifact_id = str(uuid.uuid4())
    db.insert_artifact(
        artifact_id=artifact_id,
        proposal_id=proposal.proposal_id,
        semantic_version=version,
        source_commit=commit or "",
        contract_hash=chash,
        implementation_hash=ihash,
        artifact_path=str(artifact_dir),
        verification_status="unverified",
        created_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        entry_symbols=sorted(proposal.entry_symbols),
    )

    return {
        "artifact_id": artifact_id,
        "artifact_path": str(artifact_dir),
        "wheel_path": wheel_path,
        "source_commit": commit or "",
        "version": version,
        "contract_hash": chash,
        "implementation_hash": ihash,
        "build_status": "ok",
    }


def _commit_for(db: Database, repo_id: str) -> str | None:
    return db.get_last_scanned_commit(repo_id)


def _json_dumps(obj: dict) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False)


def _build_wheel(artifact_dir: Path, dist_dir: Path) -> str:
    """Build a wheel, routing the whole build through the OS temp area.

    Some sandboxes hook ``shutil.rmtree`` and block deletions outside the OS
    temp dir (including ``python -m build``'s own ``.tmp-*`` cleanup inside
    the outdir). The artifact is copied into an OS-temp work dir, built with
    an OS-temp outdir, and only the final wheel is copied into ``dist_dir``
    (copy-only, no deletions outside the exempt zone).
    """
    import shutil
    import tempfile

    tmp_work = Path(tempfile.mkdtemp(prefix="whl-work-"))
    tmp_out = Path(tempfile.mkdtemp(prefix="whl-out-"))
    work_dir = tmp_work / "src"
    try:
        shutil.copytree(artifact_dir, work_dir)
        proc = subprocess.run(
            [sys.executable, "-m", "build", "--wheel", "--no-isolation", "--outdir", str(tmp_out)],
            cwd=str(work_dir),
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(f"wheel build failed: {proc.stderr[-600:]}")
        wheels = sorted(tmp_out.glob("*.whl"))
        if not wheels:
            return ""
        dist_dir.mkdir(parents=True, exist_ok=True)
        target = dist_dir / wheels[-1].name
        shutil.copy2(wheels[-1], target)
        return str(target)
    finally:
        shutil.rmtree(tmp_work, ignore_errors=True)
        shutil.rmtree(tmp_out, ignore_errors=True)


# ---------------------------------------------------------------------------
# render helpers
# ---------------------------------------------------------------------------

def _render_schemas(proposal: ApiProposal) -> str:
    return (
        '"""Generated request/response schemas."""\n'
        "from pydantic import BaseModel, Field\n\n\n"
        "class ApiRequest(BaseModel):\n"
        "    payload: dict = Field(default_factory=dict, description=\"request payload\")\n\n\n"
        "class ApiResponse(BaseModel):\n"
        "    result: dict = Field(default_factory=dict, description=\"response payload\")\n"
    )


def _render_adapter(import_module: str, func_name: str, params: list[tuple[str, str | None]]) -> str:
    # Single-arg functions (e.g. validators like validate_order(order: dict))
    # receive the whole payload; multi-arg functions map payload fields by name.
    if len(params) == 1:
        body = f"        {params[0][0]}=p,"
    else:
        call_args = []
        for name, default in params:
            if default is None:
                call_args.append(f'        {name}=p["{name}"],')
            else:
                call_args.append(f'        {name}=p.get("{name}", {default}),')
        # 零参数函数：body 为空，生成无参调用 func()
        body = "\n".join(call_args)
    return (
        '"""Adapter: maps the stable API payload to the legacy function."""\n'
        f"from {import_module} import {func_name}\n\n"
        "from .schemas import ApiRequest, ApiResponse\n\n\n"
        "def invoke(request: ApiRequest) -> ApiResponse:\n"
        "    p = request.payload\n"
        f"    result = {func_name}(\n"
        f"{body}\n"
        "    )\n"
        "    if result is None:\n"
        '        result = {"valid": True}\n'
        "    return ApiResponse(result=result)\n"
    )


def _render_main(proposal: ApiProposal, version: str, chash: str, ihash: str, commit: str) -> str:
    method = proposal.method.lower()
    return (
        '"""Generated FastAPI service."""\n'
        "from fastapi import FastAPI\n"
        "from .schemas import ApiRequest, ApiResponse\n"
        "from .adapter import invoke\n\n"
        f'app = FastAPI(title="{proposal.api_name}", version="{version}")\n\n'
        "SOURCE_REPOSITORY = " + repr(proposal.module_id.split(":", 1)[0]) + "\n"
        "SOURCE_COMMIT = " + repr(commit) + "\n"
        f'CONTRACT_HASH = "{chash}"\n'
        f'IMPLEMENTATION_HASH = "{ihash}"\n\n\n'
        '@app.get("/health")\n'
        "def health():\n"
        '    return {"status": "ok"}\n\n\n'
        '@app.get("/metadata")\n'
        "def metadata():\n"
        "    return {\n"
        f'        "asset_id": "{proposal.api_name}",\n'
        f'        "version": "{version}",\n'
        '        "source_repository": SOURCE_REPOSITORY,\n'
        '        "source_commit": SOURCE_COMMIT,\n'
        '        "contract_hash": CONTRACT_HASH,\n'
        '        "implementation_hash": IMPLEMENTATION_HASH,\n'
        "    }\n\n\n"
        f'@app.{method}("{proposal.path}")\n'
        "def business_endpoint(request: ApiRequest) -> ApiResponse:\n"
        "    return invoke(request)\n"
    )


def _render_contract(
    proposal: ApiProposal, import_module: str, func_name: str, signature: str,
    params: list[tuple[str, str | None]], version: str,
) -> str:
    doc = {
        "asset_id": proposal.api_name,
        "kind": "http-api",
        "version": version,
        "capability": proposal.capability,
        "entry": {
            "module": import_module,
            "function": func_name,
            "signature": signature,
            "params": [
                {"name": name, "required": default is None, "default": default}
                for name, default in params
            ],
        },
        "endpoint": {"method": proposal.method, "path": proposal.path},
        "request_schema": proposal.request_schema,
        "response_schema": proposal.response_schema,
        "source": {
            "repository": proposal.module_id.split(":", 1)[0],
            "paths": proposal.source_paths,
        },
    }
    return _json_dumps(doc)


def _render_manifest(proposal: ApiProposal, version: str, chash: str, ihash: str, commit: str) -> str:
    repo = proposal.module_id.split(":", 1)[0]
    doc = {
        "asset_id": proposal.api_name,
        "name": proposal.capability,
        "kind": "http-api",
        "version": version,
        "source": {
            "repository": repo,
            "ref": "main",
            "commit": commit,
            "paths": proposal.source_paths,
            "symbols": proposal.entry_symbols,
        },
        "contract": {"type": "openapi", "path": "openapi.json", "hash": chash},
        "implementation": {"hash": ihash},
        "generation": {"template_version": TEMPLATE_VERSION, "llm_used": False},
        "verification": {"status": "unverified"},
    }
    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


def _render_provenance(
    proposal: ApiProposal, version: str, commit: str, blob_shas: list[str],
    closure_files: dict[str, str],
) -> str:
    doc = {
        "asset_id": proposal.api_name,
        "version": version,
        "source_commit": commit,
        "source_paths": proposal.source_paths,
        "entry_symbols": proposal.entry_symbols,
        "blob_shas": sorted(blob_shas),
        "dependency_closure": sorted(closure_files.keys()),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False)


def _render_pyproject(proposal: ApiProposal, version: str, packages: list[str]) -> str:
    pkg_list = ", ".join(repr(p) for p in packages)
    name = proposal.api_name.replace("_", "-")
    return (
        "[build-system]\n"
        "requires = [\"setuptools>=68\"]\n"
        "build-backend = \"setuptools.build_meta\"\n\n"
        "[project]\n"
        f'name = "{name}"\n'
        f'version = "{version}"\n'
        'description = "Generated HTTP API asset"\n'
        'dependencies = ["fastapi>=0.141", "uvicorn>=0.52", "pydantic>=2.11"]\n\n'
        "[tool.setuptools]\n"
        f"packages = [{pkg_list}]\n\n"
        "[tool.setuptools.package-data]\n"
        'app = ["contract/*.json"]\n'
    )
